export enum HotmartSubscriptionStatusEnum {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  DELAYED = 'DELAYED',
  CANCELLED_BY_CUSTOMER = 'CANCELLED_BY_CUSTOMER',
  CANCELLED_BY_SELLER = 'CANCELLED_BY_SELLER',
  CANCELLED_BY_ADMIN = 'CANCELLED_BY_ADMIN',
  STARTED = 'STARTED',
  OVERDUE = 'OVERDUE',
}
